name: CD - Release on merge to main

on:
  pull_request:
    types: [closed]
    branches: [main]

permissions:
  contents: write

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout merged main
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          fetch-depth: 0

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "23"
          cache: maven

      - name: Run tests
        run: mvn -B -ntp test

      - name: Build package
        run: mvn -B -ntp -DskipTests package

      - name: Prepare release metadata
        id: vars
        run: |
          DATE=$(date -u +%Y%m%d-%H%M)
          SHORT_SHA=$(git rev-parse --short HEAD)
          TAG="merge-${DATE}-${SHORT_SHA}"
          NAME="Build ${DATE} (${SHORT_SHA})"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "name=$NAME" >> $GITHUB_OUTPUT
          echo "commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Create GitHub Release and upload JAR
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.vars.outputs.tag }}
          name: ${{ steps.vars.outputs.name }}
          target_commitish: ${{ steps.vars.outputs.commit }}
          prerelease: true
          generate_release_notes: true
          files: |
            target/*.jar